# Generated by Django 3.0.7 on 2020-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='team1_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2_score',
            field=models.IntegerField(null=True),
        ),
    ]
