# Generated by Django 3.0.7 on 2020-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200603_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_over',
            field=models.BooleanField(default=False),
        ),
    ]
